server:
  port: 8090
springdoc:
  swagger-ui:
    path: /
spring:
  main:
    banner-mode: off
  application:
    name: addresses-application
  data:
    mongodb:
      uri: mongodb://localhost:27017/addresses
      auto-index-creation: true
